/**
 * head.js should only return to the following tags: <title>, <meta>, <link>
 * @src https://beta.nextjs.org/docs/api-reference/file-conventions/head
 */
export default function Head() {
  return (
    <>
      <title>Create Next App</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
